import json
import random

products = []
for i in range(1, 1001):
    product = {
        "Name": f"Product {i}",
        "Description": f"Description for product {i} - Generated by AI",
        "Price": round(random.uniform(10.0, 500.0), 2),
        "Stock": random.randint(1, 100),
        "CategoryId": 1
    }
    products.append(product)

with open('bulk_products.json', 'w') as f:
    json.dump(products, f, indent=2)

print("bulk_products.json created with 1000 items.")
